// This file has been autogenerated from a class added in the UI designer.

using System;
using BigTed;
using CoreGraphics;
using Foundation;
using UIKit;

namespace SampleAzure
{
	public partial class EditEmployeeController : UIViewController
	{
		public EditEmployeeController (IntPtr handle) : base (handle)
		{
		}

		public async override void ViewDidLoad()
		{
			base.ViewDidLoad();
			var azureService = new AzureService();
			var data = await azureService.GetEmployee(Constants.Id);
			if (data != null)
			{
				TxtEmployeeName.Text = data.Name;
				TxtEmployeeDOB.Text = data.DOB.ToShortDateString();
				TxtEmployeeAge.Text = Convert.ToString(data.Age);
			}

			var btnUpdate = new UIButton(UIButtonType.Custom);
			btnUpdate.SetBackgroundImage(UIImage.FromBundle("Save"), UIControlState.Normal);
			btnUpdate.Frame = new CGRect(0, 0, 19, 19);
			btnUpdate.TouchUpInside += async (sender, e) =>
			{
				BTProgressHUD.Show("Loading", -1, ProgressHUD.MaskType.Black);
				EmployeeInfo emp = new EmployeeInfo();
				emp.Id = data.Id;
				emp.Name = TxtEmployeeName.Text;
				emp.DOB = Convert.ToDateTime(TxtEmployeeDOB.Text);
				emp.Age = Convert.ToInt32(TxtEmployeeAge.Text);
				await azureService.UpdateEmployee(emp);
				this.NavigationController.PopViewController(true);
				BTProgressHUD.Dismiss();
			};
			this.NavigationItem.SetRightBarButtonItem(null, true);
			this.NavigationItem.SetRightBarButtonItem(
				new UIBarButtonItem(btnUpdate), true);
		}
	}
}
