// This file has been autogenerated from a class added in the UI designer.

using System;
using BigTed;
using CoreGraphics;
using Foundation;
using UIKit;

namespace SampleAzure
{
	public partial class EmployeeViewController : UIViewController
	{
		public EmployeeViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			this.Title = "Employee";

			var btnSave = new UIButton(UIButtonType.Custom);
			btnSave.SetBackgroundImage(UIImage.FromBundle("Save"), UIControlState.Normal);
			btnSave.Frame = new CGRect(0, 0, 19, 19);
			btnSave.TouchUpInside += async (sender, e) =>
			{
				BTProgressHUD.Show("Loading", -1, ProgressHUD.MaskType.Black);
				EmployeeInfo emp = new EmployeeInfo();
				emp.Name = TxtEmployeeName.Text;
				emp.DOB = Convert.ToDateTime(TxtEmployeeDOB.Text);
				emp.Age = Convert.ToInt32(TxtEmployeeAge.Text);
				var azureService = new AzureService();
				await azureService.InsertEmployee(emp);
				this.NavigationController.PopViewController(true);
				BTProgressHUD.Dismiss();
			};
			this.NavigationItem.SetRightBarButtonItem(null, true);
			this.NavigationItem.SetRightBarButtonItem(
				new UIBarButtonItem(btnSave), true);
		}
	}
}
